version: '3'

services:
  db:
    container_name: $DB_CONTAINER
    image: mariadb:latest
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD

  wp:
    container_name: $WP_CONTAINER
    build: .
    depends_on:
      - db
      - cp
    restart: always
    volumes:
      - ./config/php.conf.local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./${WP_THEME}:/var/www/html/wp-content/themes/${WP_THEME}
      - ./www:/var/www/html
    environment:
      WORDPRESS_DB_HOST: $DB_CONTAINER
      WORDPRESS_DB_NAME: $DB_NAME
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_DEBUG: $WP_DEBUG
      WORDPRESS_CONFIG_EXTRA: $WORDPRESS_CONFIG_EXTRA
      WORDPRESS_TABLE_PREFIX: $WP_TABLE_PREFIX
      VIRTUAL_HOST: $VIRTUAL_HOST
      VIRTUAL_PORT: $VIRTUAL_PORT

  phpmyadmin:
    container_name: $PMA_CONTAINER
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      VIRTUAL_HOST: pma.$VIRTUAL_HOST
      VIRTUAL_PORT: $VIRTUAL_PORT
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress
      UPLOAD_LIMIT: 64M

  wpcli:
    container_name: $WPCLI_CONTAINER
    image: wordpress:cli
    volumes_from:
      - wp
    links:
      - db
    entrypoint: wp
    command: '--info'
    environment:
      WORDPRESS_DB_HOST: $DB_CONTAINER
      WORDPRESS_DB_NAME: $DB_NAME
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD

  cp:
    build: composer
    container_name: ${COMPOSER_CONTAINER}
    volumes:
      - ./www/wp-content:/app/wp-content
    command: composer install

networks:
  default:
    external:
      name: nginx_proxy
